### ISSUE TITLE
Base run generating multiple snapshot images

### ISSUE THREAD

**Issue by rileytb** [cypress-visual-regression/cypress-visual-regression#111]
When I do a base run to generate snapshots, each test is generating 2 snapshots:
- base.png
- base-*big number*.png

This creates a lot of churn in our repo because now instead of just having base.png be updated, we have a delete/create of the numbered image:
![image](https://user-images.githubusercontent.com/5489576/146037982-28dff1e4-fed5-4dba-b53a-5f0e026feefe.png)

The number changes every time I run the command to generate base images. I am using the following command to do this:

`./node_modules/.bin/cypress run --env type=base --config screenshotsFolder=cypress/snapshots/base,integrationFolder=src,testFiles=\"**/*visual.test.ts\"`

Is there a way to run the "base" command and only generate the base.png file for each test?
Thanks!

**Comment by sthuber90** [comment]
I think this is the same problem as in #76 . However the PR #35 did not  change it. Up until now @eric-burel's solution in https://github.com/mjhea0/cypress-visual-regression/issues/76#issuecomment-849726637 seems to the only thing that works. It seem that only @mjhea0 can answer what these files with the _big number_ are used for.

**Comment by rileytb** [comment]
Thanks, that definintely looks like the same issue I am seeing. Because that issue is closed (and the solution didn't really solve it), I will leave this issue open. Or should the other one be reopened where it has more history to it?

**Comment by sthuber90** [comment]
I would leave yours open. Just meant to link the other issue as reference that this still exists and hasn't been resolved

**Comment by mstalfoort** [comment]
at the moment I've fixed it (for now) this way for myself:

`npm install del-cli`

and added these commands in my `package.json` file

```json
"scripts":
        "base": "npm run create:base && npm run clean:base",
        "create:base": "cypress run --env type=base --config screenshotsFolder=cypress/snapshots/base",
        "clean:base": "del ./cypress/snapshots/base/**/*-base-[0-9]*.png",
        "clean:base:dryrun": "del ./cypress/snapshots/base/**/*-base-[0-9]*.png --dry-run"
```

which in turn gives me the following situation: I run the `npm run base` command which generates new base images (including the ones with the timestamp in it) and when that command finishes it will remove all base images which have the timestamp in it

**Comment by Big0s** [comment]
Without  any additional package: 
```
"scripts": {
        "base": "./node_modules/.bin/cypress run --env type=base --config screenshotsFolder=cypress/snapshots/base",
        "postbase": "cd cypress/snapshots/base && rm -rf */*-base-*.png"
}
```

**Comment by Zaista** [comment]
Should no longer be a problem
