### ISSUE TITLE
[Enhancement] Pixelmatch options

### ISSUE THREAD

**Issue by Big0s** [cypress-visual-regression/cypress-visual-regression#113]
Hello,
Would be nice to have possibility to pass some variables to pixelmatch f.e.`includeAA` or `diffColor` because not always default colors are best solution. 

Also can You tell me please, why to count percentage You are using ** 0.5 ?
https://github.com/mjhea0/cypress-visual-regression/blob/993b2e8f2e3887a86f0208ef082b311dce5bf504/src/plugin.js#L104

**Comment by Zaista** [comment]
2.5 years late, but still, this is now possible with `v5.2.0`
