### ISSUE TITLE
[Enhancement] Pixelmatch threshold

### ISSUE THREAD

**Issue by lgenzelis** [cypress-visual-regression/cypress-visual-regression#114]
Hey @mjhea0 ! Congrats on the awesome library, thanks a lot for creating it. This proposal is related to #113 , but I'm specifically interested in the threshold option passed to `pixelmatch`. Currently, you're using a hardcoded value of `0.1`:

```javascript
mismatchedPixels = pixelmatch(
      imgActualFullCanvas.data,
      imgExpectedFullCanvas.data,
      diff.data,
      diff.width,
      diff.height,
      { threshold: 0.1}
    );
```

It took me a while to realize why some of my tests were passing even though I had a css error which caused background differences. 😅 I'd like to be able to pass a `0` to that threshold. 

**Proposal:** let's add another parameter to `cypress-visual-regression` which is then passed as`pixelmatch` threshold.

**Comment by lgenzelis** [comment]
I created a PR, #115 , to address this proposal. I gave the new option the name `perPixelMismatchTolerance` (it's the best I could came up with.. we can't re-use `threshold` since that has a different meaning in `cypress-visual-regression`)

**Comment by DavidLS** [comment]
I'd really loved to have this implemented! Also, great library!
