### ISSUE TITLE
Beeing able to screenshot only part of the interface

### ISSUE THREAD

**Issue by bluepioupiou** [cypress-visual-regression/cypress-visual-regression#122]
I have a lot of tests in Cypress but they focus on different parts of our interface. When I want to see that a list display correctly, I try to take only it in the screenshot. Is it possible to use your comparescreenshot with css filter or directly on component like Cypress does ?

Otherwise I will have a lot of false-positive since when i'll change the tool bar, ALL the images will have regressions

Thanks in advance

**Comment by chinkjieh** [comment]
did you try `cy.get(<your selector>).compareSnapshot(snapshotName,threshold)`?

**Comment by loia5tqd001** [comment]
@chinkjieh  > did you try `cy.get(<your selector>).compareSnapshot(snapshotName,threshold)`?

it works just like `cy.compareSnapshot(snapshotName,threshold)` for me

**Comment by Zaista** [comment]
Closed due to inactivity.
