### ISSUE TITLE
TypeError: (0 , plugin_1.default) is not a function

### ISSUE THREAD

**Issue by chinkjieh** [cypress-visual-regression/cypress-visual-regression#128]
<img width="1382" alt="Screenshot 2022-05-18 at 7 42 26 PM" src="https://user-images.githubusercontent.com/7637332/169030898-90ed0f61-d1f4-4fef-a11b-d65b88b4c1f4.png">

I m having issues starting up `cypress open` with error shown above screenshot

I have added `cypress-visual-regression` to tsconfig.json
```
{
  "compilerOptions": {
    "allowJs": true,
    "target": "es5",
    "lib": ["es5", "dom"],
    "types": ["cypress", "cypress-grep", "cypress-downloadfile", "cypress-visual-regression"]
  },
  "include": ["**/*.ts"]
}
```

`e2e/cypress/support/index.js`
```
`import './commands';`
....
```

`e2e/cypress/plugins/index.js`
```
import getCompareSnapshotsPlugin from 'cypress-visual-regression/dist/plugin';

module.exports = (on, config) => {
  getCompareSnapshotsPlugin(on, config);
....
```

`e2e/cypress/support/commands.ts`
```
import compareSnapshotCommand from 'cypress-visual-regression/dist/command';
compareSnapshotCommand();
....
```

My VSCode seems to show my imports are pointing correctly to the respective files in `node_modules/cypress-visual-regression/dist/....`

Any help will be appreciated!

**Comment by chinkjieh** [comment]
solved above error with 

`e2e/cypress/plugins/index.js`
```
import * as getCompareSnapshotsPlugin from 'cypress-visual-regression/dist/plugin';
....
```

now facing
<img width="452" alt="Screenshot 2022-05-18 at 8 01 47 PM" src="https://user-images.githubusercontent.com/7637332/169034051-1d6c5e46-f65a-4a31-ba6c-65af6ad2d0f0.png">

**Comment by michal-karbasz** [comment]
I got exactly the same errors. For now, I silenced the last one by creating `/cypress/global.d.ts` with `declare module 'cypress-visual-regression/dist/plugin';`

**Comment by Zaista** [comment]
Could you try with these two options in `tsconfig.json` file:
```
"esModuleInterop": true,
"allowSyntheticDefaultImports": true,
```
And then use the normal import statement:
```
import getCompareSnapshotsPlugin from 'cypress-visual-regression/dist/plugin';
```

**Comment by iMarv** [comment]
@Zaista seems to fix it, had the same issue before.
