### ISSUE TITLE
Merging images

### ISSUE THREAD

**Issue by PetrOlliKili** [cypress-visual-regression/cypress-visual-regression#132]
Hi. 

I'm replacing cypress-image-snapshot by this plugin in our  project and i've question.

Is there any way to configure plugin to generate 'compare view' (image contains all three images: <base | diff | actual> or similar)? 
![image](https://user-images.githubusercontent.com/94967388/174617355-f0eddfb7-ddd5-410c-aeff-a09ed5b6133d.png)

Thanks

**Comment by Zaista** [comment]
Unfortunately, this is not possible atm.

**Comment by area73** [comment]
Please see my PR   https://github.com/cypress-visual-regression/cypress-visual-regression/pull/172 .
I think that with this PR  you can achieve what you are looking for 👍

**Comment by Zaista** [comment]
@area73 solution released in v3.0.0
