### ISSUE TITLE
Why does the actual directory always points to the configured screenshot directory?

### ISSUE THREAD

**Issue by jmtekin** [cypress-visual-regression/cypress-visual-regression#133]
Hi! Love the tool, great work!

When using cypress dashboard the "actual" images also get uploaded with the other screenshots since they get put in the same folder, which is undesirable.

It would be really nice to have a SNAPSHOTS_ACTUAL_DIRECTORY variable to avoid this. Is there a good reason why it doesn't exist?

**Comment by area73** [comment]
You can define:
```js
 visualRegressionBaseDirectory: 'cypress/snapshot/base',
 visualRegressionDiffDirectory: 'cypress/snapshot/diff',
```

`cypress/snapshot/actual` is used to generate the actual snapshots and compare them with the base. 
You should exclude this folder from your repo
