### ISSUE TITLE
How to integrate diff images to cypress allure report

### ISSUE THREAD

**Issue by rajkani** [cypress-visual-regression/cypress-visual-regression#138]
By default the base folder images are attached to cy.screenshot command and gets attached to allure report. But the diff images are not getting added.
Could you please add a configuration to add diff images to allure report?

**Comment by rajkani** [comment]
I'm still facing the issue with attaching the diff images to allure report, could anyone help on this issue?

**Comment by Zaista** [comment]
Integrations with other 3rd party tools, plugins or frameworks is out of the scope of this project.

Having no experience with allure reports myself, I cannot suggest any way to help out, sorry.
