### ISSUE TITLE
how to solve this error

### ISSUE THREAD

**Issue by Keerthanakiluvai** [cypress-visual-regression/cypress-visual-regression#144]
npm i -D cypress-image-diff-js
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: cypress@1.0.0
npm ERR! Found: cypress@12.1.0
npm ERR! node_modules/cypress
npm ERR!   dev cypress@"^12.0.2" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer cypress@"^9.6.1 || ^10.0.0" from cypress-image-diff-js@1.22.0
npm ERR! node_modules/cypress-image-diff-js
npm ERR!   dev cypress-image-diff-js@"*" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /home/kiluvai/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/kiluvai/.npm/_logs/2022-12-13T11_08_14_285Z-debug-0.log

**Comment by uhlstefa** [comment]
Do you use a company VPN? I have the issue that install packages wont work within the VPN as of DPI.

**Comment by Zaista** [comment]
cypress-image-diff-js? :D you're preaching to the wrong choir (wrong github project to create this issue)
