### ISSUE TITLE
Getting error: `process is not defined` while running the tests

### ISSUE THREAD

**Issue by tausif29** [cypress-visual-regression/cypress-visual-regression#153]
![image](https://user-images.githubusercontent.com/39052801/210205356-426e0ee7-21a8-40e6-b8c7-32cc2653a886.png)

I am using Cypress10 with cucumber below is my `package.json` and `cypress.config.js`

**package.json:**

![image](https://user-images.githubusercontent.com/39052801/210205828-572be0b6-3abf-4dfa-8a85-2c05616ccf2b.png)

**cypress.config.js:**
![image](https://user-images.githubusercontent.com/39052801/210205770-39b211ed-4359-4ddf-832c-01089d15a9df.png)

**Comment by area73** [comment]
Older version of Cypress and plugin, not supported
