### ISSUE TITLE
Error: `(0 , command_1.default) is not a function`

### ISSUE THREAD

**Issue by syntapy** [cypress-visual-regression/cypress-visual-regression#154]
This is preventing me from running screenshot tests at all with this lib

Although I'm not sure if this is an issue with this lib, or an instruction thats missing / off, or maybe my specific setup, but any insights are appreciated

I would be happy to try and fix myself after some discussion

# Setup

I am using Gatsby 5 with Cypress 12 and Typescript 4.9 in a Fedora 36 virtual machine

I tried following the config instructions on the README and when I run a screenshot test I get the error

```error
 1) An uncaught error was detected outside of a test

  0 passing (528ms)
  1 failing

  1) An uncaught error was detected outside of a test:
     TypeError: The following error originated from your test code, not from Cypress.

  > (0 , command_1.default) is not a function

When Cypress detects uncaught errors originating from your test code it will automatically fail the current test.

Cypress could not associate this error to any specific test.

We dynamically generated a new test to display this failure.
      at ./cypress/support/commands.ts (webpack:///./cypress/support/commands.ts:40:22)
      at __webpack_require__ (webpack:///webpack/bootstrap:19:0)
      at ./cypress/support/e2e.ts (webpack:///./cypress/support/e2e.ts:17:0)
      at __webpack_require__ (webpack:///webpack/bootstrap:19:0)
      at 0 (http://localhost:8000/__cypress/tests?p=cypress/support/e2e.ts:17747:18)
      at __webpack_require__ (webpack:///webpack/bootstrap:19:0)
      at eval (webpack:///webpack/bootstrap:83:0)
      at eval (http://localhost:8000/__cypress/tests?p=cypress/support/e2e.ts:87:10)
      at eval (<anonymous>)
```

My repo / setup for this is in [this commit](https://github.com/syntapy/superformula_clone/tree/04d65aa5fa038f9cbf395922b4bd2c78c887b9c4)

# Config

My files are

`cypress.config.ts`:
```typescript
import { defineConfig } from "cypress";
import getCompareSnapshotsPlugin from 'cypress-visual-regression/dist/plugin';

export default defineConfig({
  env: {
    screenshotsFolder: './cypress/snapshots/actual',
    trashAssetsBeforeRuns: true,
    failSilently: false,
    video: false
  },
  e2e: {
    video: false,
    baseUrl: "http://localhost:8000",
    setupNodeEvents(on, config) {
      // implement node event listeners here
      getCompareSnapshotsPlugin(on, config)
    },
  },
});
```

`cypress/tsconfig.json`
```typescript
{
  "compilerOptions": {
    "target": "es5",
    "lib": ["es5", "dom"],
    "types": [
      "cypress",
      "cypress-visual-regression",
      "node"
    ]
  },
  "include": [
    "**/*.ts"
  ]
}
```

`cypress/support/commands.ts`:
```typescript
import compareSnapshotCommand from 'cypress-visual-regression/dist/command';

compareSnapshotCommand();
```

`cypress/support/e2e.ts`:
```typescript
import './commands'
```

**Comment by okb1100** [comment]
> Hi, could you please try to add `"esModuleInterop": true` to your `cypress/tsconfig.json` file and give it a go?

Experiencing the same issue, sadly your recommendation did not help

**Comment by FakeShemp** [comment]
That solved it for me, but it had to be in the root `tsconfig.json`. Perhaps you could add this to the README?

**Comment by Zaista** [comment]
Will do, closing the issue for now.

**Comment by syntapy** [comment]
I do have that already though. Here's my `tsconfig.json`:

```json
{
  "compilerOptions": {
    "target": "esnext",
    "lib": ["dom", "esnext"],
    "jsx": "react",
    "module": "esnext",
    "moduleResolution": "node",
    "esModuleInterop": true,
    "forceConsistentCasingInFileNames": true,
    "strict": true,
    "skipLibCheck": true
  },
  "include": ["./src/**/*", "./gatsby-node.ts", "./gatsby-config.ts", "./plugins/**/*"]
}
```

Maybe the fact that I'm using Gatsby instead of like NextJS makes my setup pretty unique?

I'm having the same issue with other visual test libraries

Do you have any tips on where I can look in the code for the source of the issue?

**Comment by syntapy** [comment]
Thanks its working now!

Yeah I already had that in my root tsconfig but adding that to my cypress/tsconfig made it work like you said

**Comment by moshfeu** [comment]
> Will do, closing the issue for now.

@Zaista, can you add it to the readme? It could save me 5 minutes 😄
