### ISSUE TITLE
The "type" environment variable is unknown.  Expected: "actual" or "base"  Actual: undefined

### ISSUE THREAD

**Issue by uhlstefa** [cypress-visual-regression/cypress-visual-regression#157]
Hi,
I configured the cypress-visual-regression package as described here. But seems something in my setup is wrong.

When taking screenshot it keeps failing with: 
```
The "type" environment variable is unknown.
Expected: "actual" or "base"
Actual: undefined
```

cypress.config.js:
```
require("dotenv").config({ path: `.env${process.env.ENV_CONFIG}` });
const { defineConfig } = require("cypress");
const { beforeRunHook, afterRunHook } = require('cypress-mochawesome-reporter/lib');
const getCompareSnapshotsPlugin = require('cypress-visual-regression/dist/plugin');

module.exports = defineConfig({
  projectId: "vwviug",
  modifyObstructiveCode: true,
  chromeWebSecurity: false,

  defaultCommandTimeout: 8000,
  pageLoadTimeout: 30000,
  execTimeout: 60000,
  requestTimeout: 15000,
  responseTimeout: 15000,

  reporter: 'cypress-mochawesome-reporter',
  reporterOptions: {
    charts: true,
    reportPageTitle: 'design-system-report',
    embeddedScreenshots: true,
    inlineAssets: true,
    saveAllAttempts: false,
  },

  viewportWidth: 1000,
  viewportHeight: 600,
  waitForAnimation: true,

  retries: {
    runMode: 1,
  },
  env: {
    screenshotsFolder: './cypress/snapshots/actual',
    trashAssetsBeforeRuns: true,
    video: false
  },
  e2e: {
    setupNodeEvents(on, config) {
      getCompareSnapshotsPlugin(on, config);
      console.log(`Tests are running on ${config.env.environment} environment`);
      require('cypress-mochawesome-reporter/plugin')(on);
      require("cypress-grep/src/plugin")(config);

      on('before:run', async (details) => {
        console.log('override before:run');
        await beforeRunHook(details);
      });
      on('after:run', async () => {
        console.log('override after:run');
        await afterRunHook();
      });
      return config;
    },
    specPattern: "cypress/e2e/*.cy.js",
    supportFile: "cypress/support/e2e.js",
  },
});
```

package.json:
```
"devDependencies": {
    "cross-env": "^7.0.3",
    "cypress": "^12.2.0",
    "cypress-grep": "^3.0.3",
    "dotenv": "^16.0.3",
    "mochawesome": "^7.1.3",
    "cypress-iframe": "^1.0.1",
    "cypress-visual-regression": "2.1.0",
    "cypress-mochawesome-reporter": "^3.2.3"
  }
```

jpg files of the pages to compare are here:
..\cypress-tests\cypress\snapshots\actual

from test.js file:
cy.compareSnapshot('Button Primary'); (a file Button Primary.jpg exists in folder "actual")

I start the tests locally by using command: npx cypress open

Pls support to fix this issue! Thx

**Comment by uhlstefa** [comment]
OK, after some more investigation i figured out i need to add "--env type=actual". Now what is the difference between actual and base?

**Comment by Zaista** [comment]
The nature of this plugin (and probably all other visual-regression tools) is to have one "base" run which generates new screenshots of your application. You will assume these screenshots are how you expect your app to look like (hence the name "base"). The images generated from this run is usually something you would push to your VCS.
Then when you run tests to check for visual regression errors after some development, you will set the "actual" flag. In this case, the plugin will take new screenshots of your app, but this time it will compare them to whatever you have in your "base" folder. If the two images don't match -> visual regression issue. Hope this explains it.

**Comment by hennihaus** [comment]
Best explanation!
