### ISSUE TITLE
always creating additional folders

### ISSUE THREAD

**Issue by ac10qa** [cypress-visual-regression/cypress-visual-regression#158]
I have defined the target directories in my cypress.config.js,
but it always creates unnecessary directories. PTAL the screenshot
![image](https://user-images.githubusercontent.com/92502365/215029125-e91a7537-18ea-447e-a98f-a40664ed29ce.png)

**Comment by raimund-schluessler** [comment]
Related to https://github.com/cypress-visual-regression/cypress-visual-regression/issues/152. You need to set the environment variable `INTEGRATION_FOLDER`, that was introduced with #139 and sadly is not yet documented, to the path of your spec files, so in your case `cypress/tests/UI/` probably. Then this path gets stripped of.

**Comment by Zaista** [comment]
INTEGRATION_FOLDER added to the readme notes in the latest release
