### ISSUE TITLE
Is there a way to only regenerate/update a single base image on a test?

### ISSUE THREAD

**Issue by renatosilvatimebel** [cypress-visual-regression/cypress-visual-regression#159]
Every time that I run cypress `-e type=base` , it removes all base image files from the folders, from all specs, even if they didn't ran at all.

Is there an option to only "replace" the image that was regenerated?

**Comment by devniel** [comment]
Hello, I have the same issue, setting `-s` or `specPattern` to specific tests don´t work.

**Comment by Zaista** [comment]
Hi, I took a quick look at the [code](https://github.com/cypress-visual-regression/cypress-visual-regression/blob/master/src/plugin.js#L41) and I don't see any deletion going on... Do you mind checking if the cypress flag `trashAssetsBeforeRuns` is set to **false** (by default it's true). If it's not configured, do you mind giving it a try?

Reference: https://docs.cypress.io/guides/references/configuration#Screenshots

**Comment by derekhe** [comment]
same question
