### ISSUE TITLE
Images oddly scaled and off-center after Cypress + plugin upgrade

### ISSUE THREAD

**Issue by Josh68** [cypress-visual-regression/cypress-visual-regression#160]
Hello, and thanks for this plugin. We've been using it for over a year with no significant issues. I just upgraded the plugin and Cypress itself to v12 (latest), and now our snapshots appear to be much larger and the right sides of our pages are cut off. The only config option we have set is `{ capture: "fullPage" }`. I tried adding `{ scale: true }` and that seems to make no difference.

Has anyone else experienced this, or does anyone have ideas about what might be going on?

**Comment by Josh68** [comment]
I'm now wondering whether [this](https://github.com/cypress-io/cypress/issues/25516) is the actual issue, in Cypress.

**Comment by Zaista** [comment]
Have you managed to solve your issue, or at least, was it indeed related to cypress or not?

**Comment by Josh68** [comment]
No, but I think the issue is with Cypress, so I'm going to close this issue.
