### ISSUE TITLE
Option to not used SpecRelativePath

### ISSUE THREAD

**Issue by PetrOlliKili** [cypress-visual-regression/cypress-visual-regression#166]
Hi. 
I was looking at your code and I wonder if is a possibility to not use getSpecRelativePath() and keep 'actual' on default path generated by cypress.

I'm using after:spec and it's really annoying to find file according behavior of cypress-visual-regression plugin

Thanks

![image](https://user-images.githubusercontent.com/94967388/220922675-4324cc60-f506-40a8-9a62-04e609963e7c.png)

**Comment by PetrOlliKili** [comment]
And other thing... I found, i can use INTEGRATION_FOLDER - to reduce cypress > integration.

But why is here INTEGRATION_FOLDER, replaced and its not used path.resolve or something? https://github.com/cypress-visual-regression/cypress-visual-regression/blob/master/src/command.js#L24 

I need to define on my win `"INTEGRATION_FOLDER": "cypress\\integration",` and for linux server "INTEGRATION_FOLDER": "cypress/integration"

**Comment by Zaista** [comment]
For the first part, I can't really see the value there, shouldn't the image path be printed to log anyway?

For the second part, just an oversight regarding the cypress/integration path. Feel free to create a PR with the normalization in the meantime tho :)
