### ISSUE TITLE
I see diffs generated, but I don't see tests failing with errorThreshold 0.0

### ISSUE THREAD

**Issue by ac10qa** [cypress-visual-regression/cypress-visual-regression#168]
my command
`npx cypress run --env type=actual,qaUserName=XXXX,qaUserPassword=XXXX,configFile=qe-dev --browser=chrome --spec cypress/tests/UI/CommonFeatures/searching.spec.js`

I am calling it as `cy.compareSnapshot(getSnapshotNamePrefix() + `search-cloudACs-${k}`, 0.0)` inside my it block

which produces diff as follows
![image](https://user-images.githubusercontent.com/92502365/222217373-b862d726-9517-46e3-9d6c-78f05adddb92.png)

But doesn't fail

 (Run Finished)
     Spec                                              Tests  Passing  Failing  Pending  Skipped  
  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ ✔  searching.spec.js                        00:43        1        1        -        -        - │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘
    ✔  All specs passed!                        00:43        1        1        -        -        -

**Comment by Zaista** [comment]
Hi, difficult to say, could you share your qa-dev file, any code examples related to the plugin?

**Comment by Zaista** [comment]
Closed due to inactivity, feel free to comment here with needed info to reopen it
