### ISSUE TITLE
Error when Adding Baseline Images The following configuration option is invalid:   - testFiles

### ISSUE THREAD

**Issue by BrannonR** [cypress-visual-regression/cypress-visual-regression#171]
Hello, 

I'm fairly new to using Cypress and coding so go easy on me... I'm trying to get Visual Regression working, and I am at the point of adding baseline images but getting this error about the testFile part of adding baseline images command. I see this is due to being on a higher version of Cypress but I'm unsure what to replace on that command to get it going. 

![image](https://user-images.githubusercontent.com/125840195/224137417-91ebead9-a2f1-4a24-af2c-334873887135.png)

**Comment by Zaista** [comment]
Hi, this is more of a cypress problem and shouldn't have to do with this plugin.

Nonetheless, let me try and help: 
![image](https://user-images.githubusercontent.com/15846154/224145255-9e7b9ff0-454e-4ef8-bb21-60bc49995a15.png)

In words: in your screen shot, on the second line, I can see that the command contains the `testFiles` option as part of the `--config` flag. Just remove it, or replace it with `specPattern` :)

**Comment by BrannonR** [comment]
Thanks for the reply! I have tried that and get this error message. 
![image](https://user-images.githubusercontent.com/125840195/224148701-a283e773-f253-46a1-8c95-e09a80d14bd8.png)

**Comment by BrannonR** [comment]
I see I was missing the = after specPattern, working now! Thank you for your help!
