### ISSUE TITLE
[Enhancement] "type" var env is confusing

### ISSUE THREAD

**Issue by ger-benjamin** [cypress-visual-regression/cypress-visual-regression#173]
Hello,

I find the `type` environment variable confusing:
 - If you don't read the code, it's not clear what it does.
 - It could easily conflict with other plugin (using "`type` too).
 - It's the only one not using uppercase (`TYPE` doesn't work).

I would suggest rename it to something like: , `SNAPSHOT_FOR: [baseimage|comparison]`. That would be more understandable.
Or at least supporting `TYPE`.

**Comment by Zaista** [comment]
I agree, tho this would require a major release. I'm not against it, and it might come with the planned switch to ts and all the cleanup that's needed. When would that be I can't tell, but feel free to kick it off if you have the time
