### ISSUE TITLE
Base and Actual being saved in Base folder when running base

### ISSUE THREAD

**Issue by BrannonR** [cypress-visual-regression/cypress-visual-regression#175]
When I run the base command, its taking 2 snapshots one for base and one for actual, and saving them in the base folder. Is this normal? 

Also, is there a way it can add a date and time stamp to the name of the snapshots?

**Comment by Zaista** [comment]
Yes, that's normal, you usually wouldn't care about the actual one, and only commit base images to git.

What's the use case for having date and time stamp in the names of the snapshots? How would you expect that the base image is found during the comparison with the current one, if it contains something dynamic as the date and time? If you just need an info when this image was created, couldn't you simply refer to the git history of base images?
