### ISSUE TITLE
[Enhancements] newer version

### ISSUE THREAD

**Issue by area73** [cypress-visual-regression/cypress-visual-regression#177]
Hi @Zaista, moving forward, our previous conversation after merging this [PR](https://github.com/cypress-visual-regression/cypress-visual-regression/pull/172).

I think I can contribute to do some other changes to the code, I open this issue to let you know how I see it so we can talk about your thoughts.

These are the task that comes to my mind:

-. migrate `*.js` to `*.ts` and merge `*.d.ts` , also since we now move to TS we can  use ESM instead of commonsJS and if needed we can generate different outputs

-. Testing environment:  unit test and e2e.
I see that you were adding a docker image to run cypress and I like that idea because the plugin is meant to run on CI env, but I found it a little bit overwellm and complex when it comes the time to test and debug, especially because you have to log into the image to try to see the console logs or throw exceptions to catch the responses.
So my ideal workflow would be to have a folder with a cypress projects and run it with a npm script without mounting the docker image and then of course have a final step with a docker image to check that works on a docker image.
Also, I would try to split and simplify the way the cypress tests are running right now because we are doing the test twice (one per each type (base or actual))

-. Add other examples and use cases:
Since most of the time we want to use this plugin with a reporter like [reg-cli](https://github.com/reg-viz/reg-cli) maybe it is interesting to have a folder with examples, we don't even need to ship these examples on the package if we won't, but it will be nice for anyone to see how they can get the maximum of the plugin

-. Docs: I like the info that you have on the readme, but to me I'm missing some information about testing and debugging the plugin. In my case I had to investigate a bit about how you were doing the functional test. 

-. "type" var env is confusing #173

-. [Enhancement] Pixelmatch options #113

-. Add SNAPSHOTS_ACTUAL_DIRECTORY #133

-. Option to not used SpecRelativePath #166

Maybe you can use the Projects tab of github to create these tasks to prioritize  and follow conversations there or whatever you fill it could help us to communicate.

**Comment by Zaista** [comment]
I can't create new projects since I'm not the owner (or missing the privileges). Let's kick it off here, and I'll see about getting them, would be nice to have a decent overview, so something like this:
[ ] Set up a project to track tasks easily

**Comment by mrhyde** [comment]
@area73 I hope you don't mind me taking the migration task :) https://github.com/cypress-visual-regression/cypress-visual-regression/pull/183

**Comment by mrhyde** [comment]
@area73 Yeah, lets' do that
I checked both this repo and your profile looking if someone was working on it already but since nothing was pushed to GitHub I figured nobody was working on it :(

**Comment by area73** [comment]
A newer version was deployed with the above suggestions.
Closing issue
