### ISSUE TITLE
Add the command to cypress/support/commands.js no work

### ISSUE THREAD

**Issue by hongdeyuan** [cypress-visual-regression/cypress-visual-regression#178]
Hi! Love the tool；but, problems found with the latest version;
- cypress version: 12.7.0
- cypress-visual-regression version: 3.0.0

config:
```
// cypress/tsconfig.json
{
  "compilerOptions": {
    "types": ["cypress", "cypress-visual-regression"]
  },
  "include": ["**/*.ts"]
}
```

```
// cypress/cypress.config.ts
import compareSnapshotCommand from 'cypress-visual-regression/dist/command';

compareSnapshotCommand();

```

```
//cypress/cypress.config.ts
import { defineConfig } from 'cypress';
import getCompareSnapshotsPlugin from 'cypress-visual-regression/dist/plugin';

export default defineConfig({
  env: {
    screenshotsFolder: './cypress/snapshots/actual',
    trashAssetsBeforeRuns: true,
    video: false,
  },
  e2e: {
    setupNodeEvents(on, config) {
      getCompareSnapshotsPlugin(on, config);
    },
  },
});
```

error:

![image](https://user-images.githubusercontent.com/37143703/226584961-a3cd6998-3ada-475c-b4ab-576f4edaff58.png)

**Comment by zkarsli61** [comment]
Hi, It's a closed issue. Could you pls try this? 
https://github.com/cypress-visual-regression/cypress-visual-regression/issues/154#issuecomment-1374827306

**Comment by hongdeyuan** [comment]
> Hi, It's a closed issue. Could you pls try this? [#154 (comment)](https://github.com/cypress-visual-regression/cypress-visual-regression/issues/154#issuecomment-1375431421)

Thanks, that solved it for me
