### ISSUE TITLE
[BUG] Wrong screenshot position

### ISSUE THREAD

**Issue by Lultik** [cypress-visual-regression/cypress-visual-regression#181]
If I set viewportHeight param more the height of cypress window size, .compareSnapshot command captures screenshots in wrong place.
It captures screenshot lower than expected.

Steps to reproduce:
1. Set `viewportHeight` more than window of cypress browser height (for example, 1080);
2. Make screenshot of component (not full screen) (I tried do it on Modal component, that placed in the middle of screen)

**Actual result:**
Screenshot contains only part of component.
**Expected result:**
There is only component in screenshot.

**Comment by hongdeyuan** [comment]
+1

**Comment by area73** [comment]
@Lultik , @hongdeyuan , can you provide us with a working example?

Thanks

**Comment by firestar300** [comment]
Hi @area73 ,

This is my e2e tests.

```js
import fixtures from '../fixtures/screenshots/fixtures'

const SITE_NAME = Cypress.env('SITE_NAME') || 'omneseducation'
const SITE_ENV = Cypress.env('SITE_ENV') || 'production'

describe("Screenshot non regression", () => {
  context('iPhone XR', () => {
    beforeEach(() => {
      // run these tests as if in a desktop
      cy.viewport('iphone-xr')
    })

    compareSnapshotsTest('iPhone XR')
  })

  context('macbook-16', () => {
    beforeEach(() => {
      // run these tests as if in a desktop
      cy.viewport('macbook-16')
    })

    compareSnapshotsTest('720p resolution')
  })
})

function compareSnapshotsTest(viewport) {
  const site = fixtures[SITE_NAME]
    const lazyElements = ['.list-article-item']

    site.pages.forEach(page => {
      it(`Snapshot [${SITE_NAME}]: ${SITE_ENV} — ${page.name}`, () => {
        cy.visit(site[SITE_ENV].url + page.url, {failOnStatusCode: false})

        cy.get('body').then($body => {
          for (const lazyElement of lazyElements) {
            if (!$body.find(lazyElement, {
              timeout: 100
            }).length) {
              return
            }

            cy.get(lazyElement).each($el => {
              cy.wrap($el).scrollIntoView({duration: 100})
            })
          }
        })

        cy.compareSnapshot(`${page.name}-${viewport}`, {
          capture: 'fullPage',
          errorThreshold: 0.5,
          timeout: 1200000,
        }).then(comparisonResults => {
          console.log(comparisonResults.mismatchedPixels) // will print the number of mismatched pixels
          console.log(comparisonResults.percentage) // will print the percentage of mismatched pixels
          console.log(comparisonResults.error) // will print the visual regression error message (if any)
        })
      })
    })
}
```

When i set the `macbook-16` viewport according to [Cypress documentation](https://docs.cypress.io/api/commands/viewport), my screenshot is cropped.

![front-page-720p resolution](https://github.com/cypress-visual-regression/cypress-visual-regression/assets/2543936/78a45c27-309a-41af-90bc-db85266a94fd)

**Comment by area73** [comment]
Hey @firestar300, are you using a Mac book pro to generate the screenshots?
If so, can you try to launch Cypress snapshots on another laptop (not Mac Book Pro) or if you don't have another laptop but you do have an external monitor, try to launch the Cypress snapshots from the external monitor (having the main window in that external monitor and closing the laptop.

Most of these issues are related to Macbook retina display.

Also, have a look at this issue 
https://github.com/cypress-visual-regression/cypress-visual-regression/issues/165.
