### ISSUE TITLE
The "type" environment variable is unknown.

### ISSUE THREAD

**Issue by jekajolob** [cypress-visual-regression/cypress-visual-regression#182]
Please can anyone help me?

Steps to reproduce:
1. Installed Cypress Visual Regression plugin
`npm install cypress-visual-regression`
2. Add the following config to your cypress.config.js file:
![image](https://user-images.githubusercontent.com/26455770/229241027-92c96bfe-369c-4000-8011-8350d9c5a86a.png)
3. Add the command to cypress/support/commands.js:
![image](https://user-images.githubusercontent.com/26455770/229241116-1711aecb-ce42-4b52-8e18-12dba72cd714.png)
4. Added {visual.cy.js} test to cypress/e2e/
![image](https://user-images.githubusercontent.com/26455770/229241262-c02ed3ef-b9eb-45c8-be44-ca25bbbf6c92.png)
5. Ran the test and received the error:
![image](https://user-images.githubusercontent.com/26455770/229241385-909d65e9-997f-4829-af77-3505c35fe5ab.png)

**Comment by Zaista** [comment]
Had the same issue the first time I used this plugin (facepalm). We'll document this better, but for now, just add the type env variable, like so:

In your `cypress.config.ts`:
```
env: {
    type="base"
}
```
Use `base` to create initial screanshoots, and then use `actual` to test against those base images.

Or in your run command, for exaple:
```
cypress run --env type=base
```
