### ISSUE TITLE
`env` object in config file or not?

### ISSUE THREAD

**Issue by pbb72** [cypress-visual-regression/cypress-visual-regression#186]
The TypeScript configuration file in the README.md puts several configuration options in an `env` object:

```ts
export default defineConfig({
  env: {
    screenshotsFolder: './cypress/snapshots/actual',
    trashAssetsBeforeRuns: true,
    video: false
  },
  ...
});
```

But the JavaScript version does not:

```javascript
module.exports = defineConfig({
  screenshotsFolder: './cypress/snapshots/actual',
  trashAssetsBeforeRuns: true,
  video: false,
  ...
});
```

Is this a deliberate distinction, or is it an error?

**Comment by Josh68** [comment]
No reference to `.env` [here](https://github.com/cypress-visual-regression/cypress-visual-regression/blob/62b710bdf76f72e54d207a9b7eac36fac46dd503/src/plugin.js#L22) or [here](https://github.com/cypress-visual-regression/cypress-visual-regression/blob/62b710bdf76f72e54d207a9b7eac36fac46dd503/docker/cypress.config.js#L6)
