### ISSUE TITLE
Base screenshot doesnt get the full screen

### ISSUE THREAD

**Issue by anselmbradford** [cypress-visual-regression/cypress-visual-regression#196]
I am seeing https://github.com/cypress-io/cypress/issues/1857 when capturing base images. So the images are twice the expected size (because retina) and offset from center. Any hunch as to why that may be?

**Comment by area73** [comment]
Yes we notice that, but that is a problem with Mac Book Pro and retina display with cypress ( not with the plugin).

If you are using chrome to run cypress then you can lunch your test with : --force-device-scale-factor=1. (or 2 depends if you want to have double the size or normal size)
```js
// plugins/index.js
module.exports = (on, config) => {
  on('before:browser:launch', (browser = {}, launchOptions) => {
    if (browser.family === 'chromium' && browser.name !== 'electron') {
      launchOptions.args.push('--force-device-scale-factor=2')
    }
    return launchOptions
  })
}
```
You have more info here:

https://github.com/cypress-io/cypress/issues/6485#issuecomment-655536907


On the other hand if you are running cypress with electron, then I couldn't find a way to set the scale factor. The work around that I used is that if you have an external monitor then run your cypress test with the external monitor set as primary monitor, or use a docker image to solve this and other problems that may arise when running on the CI.

If anyone else has a suggestión please post it here , thanks 👍
