### ISSUE TITLE
cypress-mochawesome-reporter failing when used with cypress-visual-regression

### ISSUE THREAD

**Issue by Subir-Saw** [cypress-visual-regression/cypress-visual-regression#214]
_Cypress-mochawesome-reporter_ throws exception when used together with _cypress-visual-regression_. _Cypress-visual-regression_ moves the screenshot captured to a different location leading to _cypress-mochawesome-reporter_ not being to able to locate the screenshot at the original location which in turn is leading to the exception as the reporter needs the location of the screenshot to embed in the HTML report.

**Comment by Zaista** [comment]
Hi, we are release soon a new version, and this should no longer be an issue

**Comment by Subir-Saw** [comment]
Thanks @Zaista. Do you have tentative timeline for the release?

**Comment by Zaista** [comment]
Released just now: v4.0.0
