### ISSUE TITLE
`getSpecRelativePath()` returns invalid path on windows based hosts

### ISSUE THREAD

**Issue by Dragas** [cypress-visual-regression/cypress-visual-regression#218]
In command.js, `getSpecRelativePath()` function there's a following snippet of code
```js
function getSpecRelativePath() {
  const integrationFolder = getValueOrDefault(Cypress.env('INTEGRATION_FOLDER'), 'cypress/e2e');
  return Cypress.spec.relative.replace(integrationFolder, '');
}
```
The attempts function to replace base folder of a given test with an empty string. The problem is that on windows hosts, that directory ends up being `cypress\e2e`, and the replacement function fails. This prompts a further problem, where `INTEGRATION_FOLDER` environment variable must be system specific.

Finally, upon inspecting the deployed version to npm registry and the one provided by the repository I see that the command.js file does not match in content. How come?

**Comment by area73** [comment]
Hey @Dragas, we are in the middle of a big release adding TS and refactoring some things, in the new release we don't have this function anymore.
You can check the new release under [migration](https://github.com/cypress-visual-regression/cypress-visual-regression/blob/migration/src/command.ts), to see if that meets your requirements.

**Comment by user4i** [comment]
So in new versions we should anyway have long path like `snapshots/cypress/e2e/SomeModule/Some.spec.js` ? And no options to remove this deeping path part `cypress/e2e` or other by tests location? Thank you.
