### ISSUE TITLE
Compare a single HTML element is not working as expected

### ISSUE THREAD

**Issue by georgekaran** [cypress-visual-regression/cypress-visual-regression#219]
## Description

When using the `.compareSnapshot()` method on a chainable element, a full-page screenshot is taken instead of just the element.

Example:
```tsx
cy.findByRole('dialog', {name: 'my-dialog'})
    .compareSnapshot('my-dialog')
// or    
cy.get('[role="dialog"][aria-label="my-dialog"]')
    .compareSnapshot('my-dialog')
```

## Expected behavior
The screenshot should only include the chainable element instead of capturing the entire page.

## Context
Calling `cy.compareSnapshot('page')` to take a full-page screenshot does work as expected

## Environment

| Package | Version |
|--------|--------|
| cypress-visual-regression | 2.1.1 |
| cypress | 12.17.4 |
| Firefox | 117 | 
| Chrome | 107 |

**Comment by area73** [comment]
Can you please try to update to version 3.

If you still have that issue can you provide a working example.

Thanks 👍

**Comment by georgekaran** [comment]
Hey, sorry I've forgot to include this in the context, but I did try upgrading cypress-visual-regression to the latest version, still did not work.

I'll try to create a public working example.

**Comment by georgekaran** [comment]
Hey everyone, just wanted to give an update. 

We found a configuration issue in our step to compare the snapshot, which was causing the problem. Luckily, we were able to address the issue, and everything is now working perfectly!

**Comment by area73** [comment]
Hey @georgekaran, we are planning to add a new project with configuration best practices to use the plugin because we found out that there are a lot of things that we should take care of to have success with the snapshots, so please stay tuned and feel free to add any issue that you may find relevant.
Cheers
