### ISSUE TITLE
No option to override test type through CLI in v4

### ISSUE THREAD

**Issue by TomaszG** [cypress-visual-regression/cypress-visual-regression#223]
Since v4, the test type is now defined by a variable inside the `visualRegression` object instead of a simple `type` variable. This, unfortunately, blocks the possibility of controlling the test type through Cypress CLI. According to [Cypress docs for Environment Variables](https://docs.cypress.io/guides/guides/environment-variables#Option-4---env), the `--env` and `CYPRESS_` options do not work for nested variables. The only option is to use a separate config file, which is an overkill for one variable (as it's mentioned in the linked docs).

**Comment by area73** [comment]
@Zaista , I will take a look at this issue.
@TomaszG , thanks for reporting

**Comment by Zaista** [comment]
In the meantime, you can use old variables, as they were just deprecated, not removed

**Comment by area73** [comment]
@TomaszG , new PR made with the changes:

Now any config key will have a **namespace** and will follow **camelCase** notation:
```
env: {
  visualRegressionType: TypeOption
  visualRegressionBaseDirectory?: string
  visualRegressionDiffDirectory?: string
  visualRegressionGenerateDiff?: DiffOption
  visualRegressionFailSilently?: boolean
} 
```
The bad thing is that we will need to update the plugin to a major version 🥴 (V 5.0.0)

**Comment by Zaista** [comment]
This issue should be resolved in the v5, please check it out and let us know if you come up with any other issues. Appreciate it for raising this one.
