### ISSUE TITLE
[v4] Spec directory not included in screenshot path

### ISSUE THREAD

**Issue by TomaszG** [cypress-visual-regression/cypress-visual-regression#225]
In v3 the spec path was respected when resolving screenshot paths. In v4, the spec path is ignored; the plugin looks for screenshots in the root of the provided screenshots paths.

**Repro steps:**
1. Create spec in a directory that is in the e2e directory, e.g. `cypress/e2e/somedir/some.spec.js`
2. Use the plugin in test in it, e.g.
```
describe('test', () => {
	it('tests path', () => {
		cy.visit('https://example.cypress.io')
		cy.compareSnapshot('example-snapshot.png')
	})
})
```

**Current (v4) result:**
The plugin looks for snapshots in `./cypress/snapshots/actual/some.spec.js/example-snapshot.png`

**Expected (v3) result:**
The plugin respects the spec path, so it looks for a snapshot in `./cypress/snapshots/actual/somedir/some.spec.js/example-snapshot.png`

**Comment by Zaista** [comment]
Thanks for raising this issue. Is there any specific need to have this behavior the same as in v3? Because with Cypress' `specPattern` option it's difficult to predict the location of spec files, hence the base folder was used with no nesting.

In hindsight, the thing I obviously missed is to make this visible for users who upgrade.

**Comment by TomaszG** [comment]
Personally, I don't, I can live with that :) However, I can imagine a scenario where one has the same spec names in different directories so they will have to remember to use unique snapshot names in specs so they don't conflict across these specs.

**Comment by area73** [comment]
Hey @TomaszG , @lamberski I will take a look at this issue soon, Thanks for reporting
cc: @Zaista
