### ISSUE TITLE
Path issue with component testing

### ISSUE THREAD

**Issue by johnkim-det** [cypress-visual-regression/cypress-visual-regression#229]
Trying to use this library for visual regression in component testing.

With these values in `cypress.config.ts`:

```
  component: {
    devServer: {
      framework: 'react',
      bundler: 'vite',
    },
    env: {
      visualRegressionType: 'regression',
      visualRegressionBaseDirectory: 'cypress/snapshot/base',
      visualRegressionDiffDirectory: 'cypress/snapshot/diff',
      visualRegressionGenerateDiff: 'always',
      visualRegressionFailSilently: true,
    },
    screenshotsFolder: './cypress/snapshots/base',
    setupNodeEvents(on, config) {
      configureVisualRegression(on);
    },
  },
```

and a test `Modal.cy.tsx` calling `cy.compareSnapshot('Modal')`, I get an error that looks like this:

```
cy.task('compareSnapshots') failed with the following error:

> File '/cypress/snapshots/base/Modal.cy.tsx/Modal.png' does not exist.
```

The screenshots are saved to the top-level `/cypress/snapshot/base`, but the comparison task is looking for a subfolder named after the test. Is there a way to make sure the task looks for the screenshot in the same place they're saved?

**Comment by area73** [comment]
I think you have an extra "s" character on snapshot in  `screenshotsFolder` key

You are using :
```json
      visualRegressionBaseDirectory: 'cypress/snapshot/base',
      visualRegressionDiffDirectory: 'cypress/snapshot/diff',
```
and 
```json
screenshotsFolder: './cypress/snapshots/base',
```

**Comment by nemonemi** [comment]
I'm seeing the same error. Where did you notice the extra "s" character, @area73?

I'm using this with Cypress Components and this is my setup

export default defineConfig({
    component: {
        devServer: {
            framework: "react",
            bundler: "vite",
        },
        env: {
            visualRegressionType: "regression",
        },
        screenshotsFolder: "./cypress/snapshots/actual",
        setupNodeEvents(on) {
            configureVisualRegression(on);
        },
    },
});

And in the test:

```
cy.compareSnapshot("zzz");
```

I get 

```
cy.task('compareSnapshots') failed with the following error:

> File '/home/develop/other/fe-components/cypress/snapshots/base/SingleSelectableOption.cy.tsx/zzz.png' does not exist.
```

**Comment by area73** [comment]
@nemonemi , here:

screenshotsFolder: "./cypress/snapshots/actual",

**Comment by nemonemi** [comment]
@area73, thanks for that awesomely quick response!

I see that location in the code, but not the extra "s".

**Comment by Colombo97** [comment]
That is happening here too

**Comment by Colombo97** [comment]
@nemonemi, have you solved it?

**Comment by nemonemi** [comment]
Nope, I have not.

**Comment by area73** [comment]
Can you provide a working environment to test it?

Thanks
