### ISSUE TITLE
Releases documentation

### ISSUE THREAD

**Issue by nemonemi** [cypress-visual-regression/cypress-visual-regression#236]
Hello good sirs/madams,
What is the release strategy of your library? Is there some way to see the changes between versions?

**Comment by area73** [comment]
Hi @nemonemi , you can check our [changelog.md](https://github.com/cypress-visual-regression/cypress-visual-regression/blob/master/CHANGELOG.md)

**Comment by nemonemi** [comment]
Much obliged!
