### ISSUE TITLE
Screenshots Differ Across Resolutions

### ISSUE THREAD

**Issue by bbkx226** [cypress-visual-regression/cypress-visual-regression#237]
## Problem
When employing the `cypress-visual-regression` plugin for testing, I've encountered a notable issue with discrepancies in screenshots captured across devices with varying resolutions. Interestingly, despite setting the viewport of Cypress to `1920x1080`, the problem persists. Tests execute smoothly on my `1920x1080` resolution device, yet inconsistencies between the base and actual screenshots emerge when transitioning to another device with a distinct resolution (in my case, `2550x1440`). These disparities ultimately lead to test failures, complicating the reliability of visual regression testing across multiple devices.

One of the failed tests:
![image](https://github.com/cypress-visual-regression/cypress-visual-regression/assets/83408362/f4a37251-4a6f-453c-9b15-996b27ecfdd4)

Error on Cypress UI Console:
![image](https://github.com/cypress-visual-regression/cypress-visual-regression/assets/83408362/0f61c19c-a7b8-4c79-becf-9cbd8119d72f)

Related Code:
![image](https://github.com/cypress-visual-regression/cypress-visual-regression/assets/83408362/8e5f59d4-f93c-4e5a-9d57-29642a3562f5)

## Expected Behavior
The screenshots captured during testing should remain consistent across devices with varying resolutions, ensuring accurate comparison and reliable test results regardless of the device used.

## Steps to Reproduce
1. Set up Cypress plugin for testing.
2. Set up the viewport of Cypress to `1920x1080`
3. Run tests on a device with resolution A (e.g., 1920x1080).
4. Observe and record the screenshots captured during testing.
5. Switch to a device with resolution B (e.g., 2550x1440).
6. Run the same tests on the device with resolution B.
7. Compare the screenshots captured during testing on devices A and B.
8. Note the discrepancies between the base and actual screenshots.

**Comment by eugenet8k** [comment]
I had similar issues and noticed that this could be a Cypress-related issue, as that is where essentially a screenshot is being taken. This library just handles files and a few other nuances, but does not really take screenshots into PNG.

**Comment by bbkx226** [comment]
> I had similar issues and noticed that this could be a Cypress-related issue, as that is where essentially a screenshot is being taken. This library just handles files and a few other nuances, but does not really take screenshots into PNG.

Yup, I've come to the conclusion that it's something related to Cypress. It works well on my 1920x1080 resolution laptop, but it turns out to fail on a 2550x1440 resolution monitor, even if I generate the base image using 2550x1440 and test it in the same resolution. Interestingly, when I zoom out the Chrome browser to around 80% while testing, the actual threshold limit value decreases, and some tests might even pass.

**Comment by area73** [comment]
I don't know if this is the same issue but if you run your test on a Mac with retina display your snapshots are going to be double size ( do to Cypress and Chrome config).

**Comment by Zaista** [comment]
Different resolutions naturally generate different looking UIs, this is neither a bug nor the Cypress problem. If you want to test different resolutions, then you have to generate dedicated base images for all different resolutions you want. You can parameterize this if you want to run the same test for all the different resolutions, but you HAVE to generate dedicated base images for all of them.
