### ISSUE TITLE
Spec folder is not being respected when generating a snapshot

### ISSUE THREAD

**Issue by eugenet8k** [cypress-visual-regression/cypress-visual-regression#238]
Before the update to v5, in v3 the behavior was that file structure was preserved. For example I had all base and actual snapshots generated following the same dir structure of my cypress tests

```
/cypress
   /e2e
       /special
          special.cy.js
       catch-all.cy.js
```

the output would be

```
/cypress
   /e2e
       /special
          /special.cy.js
              snapshot1.png
       /catch-all.cy.js
           snapshot2.png
```

now it is

```
/cypress
   /e2e
       /special.cy.js
           snapshot1.png
       /catch-all.cy.js
           snapshot2.png
```

basically my nested directory `/special` is ignored. I believe this is due to the change in this code, where `args.specFolder` was respected:

https://github.com/cypress-visual-regression/cypress-visual-regression/blob/97e69afa0f9e81a14fa30c6b02f3c9ce561c792e/src/plugin.ts#L30-L33

now it is not:

https://github.com/cypress-visual-regression/cypress-visual-regression/blob/811d77cef2d5023b72ccec2604efdf8e116626d5/src/plugin.ts#L55

**Comment by Zaista** [comment]
This should be solved now, even before `v5.2.0`. Please let me know if some issues still persist
