### ISSUE TITLE
Updating base screenshot when regression test failed

### ISSUE THREAD

**Issue by user4i** [cypress-visual-regression/cypress-visual-regression#256]
It would be great to have such config option to replace base snapshot when regression test filed and we agree with change.

So if regression failed we replace base file with actual. And git will help to control and apply only good changes.

Why?:

1. When we see difference between base and actual we should be sure that we replace base with same behavior, because next time it can be other behavior and not same snapshot and not sure correct. 
2. At updating base snapshots some of it can be crashed but we want to update only 
3. Updating base can change bits and bytes without changing pixels and we should fix this 
4. If we keep snapshots in git, it helps us to agree or not with changed base and be sure in update base.

**Comment by Zaista** [comment]
Hi, I'm really not sure if I understand what you'd like to achieve.
As far as I can tell, using the plugin in the intended way would cover all of those points properly.
Perhaps you could consult the README file again, and point out any unclear parts?
