### ISSUE TITLE
Error when using cy.log on 5.0.4

### ISSUE THREAD

**Issue by chabb** [cypress-visual-regression/cypress-visual-regression#264]
This error happens on 5.0.4
 
 The task 'log' was not handled in the setupNodeEvents method. The following tasks are registered: compareSnapshots, updateSnapshot

It does not happen on 5.0.0

**Comment by Zaista** [comment]
I'm having trouble reproducing this. I have a hunch which part of the code might cause it, which will be removed in the next version. It will be published any day now, then we can check

**Comment by chabb** [comment]
Sounds good, I’ll check the new version

**Comment by skjnldsv** [comment]
Any news on the new version @Zaista ?

**Comment by fskarmeta** [comment]
hey there, also experiencing this issue :) 
Works fine when using cypress UI but on CI run it fails.

**Comment by Zaista** [comment]
Can you please try with `v5.1.0`? Otherwise I'd need some help reproducing it

**Comment by chabb** [comment]
It's fixed on 5.1.0 @Zaista
