### ISSUE TITLE
Default errorThreshold not respected

### ISSUE THREAD

**Issue by benthieu** [cypress-visual-regression/cypress-visual-regression#267]
Somehow the latest version 5.2 does not respect the default errorThreshold defined in `addCompareSnapshotCommand`

Could you take a look at this?

**Comment by Zaista** [comment]
Thanks for raising the issue, somehow missed it. Should be fixed with `v5.2.1`

**Comment by benthieu** [comment]
Thanks a lot for the fast reply and fix
