### ISSUE TITLE
How to replace existing screenshots when a user has added new data to a feature?

### ISSUE THREAD

**Issue by olivernosto** [cypress-visual-regression/cypress-visual-regression#278]
While the regression analysis is extremely helpful, I would love to know what the best method of allowing the engineers on our team to refresh their snapshots when they introduce new features.

When updating the visualRegressionType property from 'regression' to 'base', I know this will generate new ones,
but in tools like jest theres generally a command like --updateSnapshots.

Is there something similar here?

Thanks!

**Comment by Elte156** [comment]
@olivernosto there is this description from https://github.com/cypress-visual-regression/cypress-visual-regression/issues/157#issuecomment-1403835145

Seems like you would inject the flag `--env visualRegressionType=base` when running the `cypress` command.

**Comment by Zaista** [comment]
As @Elte156 mentioned, yep, this is the way to do it: Run tests locally with the `base` flag, then push updated base images.
